In [2]:
# Create a 5 × 5 NumPy matrix containing numbers from 1 to 25 and print: ○ The first row ○ The last column ○ The diagonal elements 
import numpy as np

# 1. Create a 5x5 matrix containing numbers from 1 to 25
matrix = np.arange(1, 26).reshape(5, 5)
print("Original 5x5 Matrix:")
print(matrix)


# 2. Print the first row (Index 0)
first_row = matrix[0, :]
print("First Row:")
print(first_row)


# 3. Print the last column (Index -1)
last_column = matrix[:, -1]
print("Last Column:")
print(last_column)


# 4. Print the diagonal elements
diagonal_elements = np.diag(matrix)
print("Diagonal Elements:")
print(diagonal_elements)

Original 5x5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First Row:
[1 2 3 4 5]
Last Column:
[ 5 10 15 20 25]
Diagonal Elements:
[ 1  7 13 19 25]


In [8]:
#Create two 3 × 3 matrices and perform matrix addition, subtraction, and matrix multiplication.
matrix1 = np.arange(1, 10).reshape(3, 3)
matrix2 = np.arange(1, 10).reshape(3, 3)
print("matrix addition:\n", matrix1+matrix2)
print("matrix substraction:\n", matrix1-matrix2)
print("matrix multiplication:\n", matrix1@ matrix2)




matrix addition:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
matrix substraction:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
matrix multiplication:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [15]:
#Create a NumPy array of numbers from 1 to 100 and print all numbers divisible by 3 using Boolean indexing.
arr= np.array(range(1,101))
print("numpy array:\n", arr) 
mask = (arr%3==0)
print("all numbers divisible by 3 using Boolean indexing:")
print(arr[mask])

numpy array:
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
all numbers divisible by 3 using Boolean indexing:
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [25]:
# Create a 4 × 4 matrix and replace all even numbers with 0. 
matrix=np.array(range(1, 17)).reshape(4,4)
mask = (arr%2==0)
matrix[mask]=0
print(matrix)


[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [ ]:
#Create a 5 × 5 matrix of random integers and find: ○ Maximum value ○ Minimum value ○ Mean ○ Median 
matrix=np.random.randint(1,26, 25).reshape(5,5)
print(matrix)
print("maximum value:", np.max(matrix))
print("minimum value:", np.min(matrix))
print("mean value:", np.mean(matrix))
print("median value:", np.median(matrix))


[[16 14  7 17  1]
 [13  9 10 20  6]
 [ 6  8  2 15 25]
 [25 10  3  3 12]
 [24  5  1 16  3]]
maximum value: 25
minimum value: 1
mean value: 10.84
median value: 10.0


In [38]:
#Create a NumPy array containing 20 random numbers and sort it in ascending and descending order. 
arr=np.random.randint(1,50,21)
print(arr)
print("ascending order:", np.sort(arr))
print("descending order:", np.sort(arr)[::-1])


[14  3  6 40 28 14 28  7 30 36 11 42  3 39 17 26 41 15 48 29 13]
ascending order: [ 3  3  6  7 11 13 14 14 15 17 26 28 28 29 30 36 39 40 41 42 48]
descending order: [48 42 41 40 39 36 30 29 28 28 26 17 15 14 14 13 11  7  6  3  3]


In [43]:
#Create a 6 × 6 matrix and print: ○ Main diagonal ○ Upper triangular part ○ Lower triangular part 
matrix=np.random.randint(1,26, 25).reshape(5,5)
print(matrix)
print("main diagonal:", np.diag(matrix))
print("upper triangular part:\n", np.triu(matrix))
print("lower triangular part:\n", np.tril(matrix))

[[13 16  4 20 12]
 [17 12 18 15 19]
 [12 20 16 17  5]
 [18 16  9  1 24]
 [15 21 22 10 21]]
main diagonal: [13 12 16  1 21]
upper triangular part:
 [[13 16  4 20 12]
 [ 0 12 18 15 19]
 [ 0  0 16 17  5]
 [ 0  0  0  1 24]
 [ 0  0  0  0 21]]
lower triangular part:
 [[13  0  0  0  0]
 [17 12  0  0  0]
 [12 20 16  0  0]
 [18 16  9  1  0]
 [15 21 22 10 21]]


In [49]:
#Create a NumPy array of 20 elements and reshape it into: ○ 4 × 5 matrix ○ 2 × 10 matrix ○ 5 × 4 matrix
arr=np.array(range(1,21))
print("\n",arr)
arr1=np.array(range(1,21)).reshape(4,5)
print("\n", arr1) 

arr1=np.array(range(1,21)).reshape(2,10) 
print("\n", arr1)
arr1=np.array(range(1,21)).reshape(5,4) 
print("\n", arr1)



 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [52]:
# Create a 5 × 5 matrix and calculate the sum of: ○ Each row ○ Each column
matrix=np.array(range(1,26)).reshape(5,5)
print(matrix)
print("\n", np.sum(matrix, axis=0))
print("\n", np.sum(matrix, axis=1))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

 [55 60 65 70 75]

 [ 15  40  65  90 115]


In [55]:
#Create two arrays and find all common elements between them.
arr=np.array(range(1,10))
arr1=np.array(range(5,15))
print(np.intersect1d(arr1, arr))

[5 6 7 8 9]


In [65]:
#Create a 5 × 5 matrix and find the position (row and column index) of the largest element. 
matrix=np.random.randint(1,26, 25).reshape(5,5)
print(matrix)
print("maximum value:", np.max(matrix))
fi=np.argmax(matrix)
row_idx, col_idx = np.unravel_index(fi, matrix.shape)
print(f"Flat Index position: {fi}")
print(f"2D Coordinates -> Row Index: {row_idx}, Column Index: {col_idx}")

[[ 8 12 17  4 10]
 [19 25 11 14  1]
 [ 7  5 17  3 13]
 [ 5  9 13  8 17]
 [25 23 15 13 10]]
maximum value: 25
Flat Index position: 6
2D Coordinates -> Row Index: 1, Column Index: 1


In [66]:
#Create a dataset of students' marks using a NumPy array and find: ● Highest marks ● Lowest marks ● Average marks ● Students scoring above average 

np.random.seed(7)
marks = np.random.randint(40, 100, size=15)

print("Students' Marks Dataset:")
print(marks)
print("-" * 45)

# 2. Find Highest, Lowest, and Average marks
highest_marks = np.max(marks)
lowest_marks = np.min(marks)
average_marks = np.mean(marks)

print(f"Highest Marks : {highest_marks}")
print(f"Lowest Marks  : {lowest_marks}")
print(f"Average Marks : {average_marks:.2f}")
print("-" * 45)

# 3. Find students scoring above average using boolean indexing
above_average_mask = marks > average_marks
students_above_avg = marks[above_average_mask]

print(f"Number of students scoring above average: {len(students_above_avg)}")
print("Marks of students scoring above average:")
print(students_above_avg)

Students' Marks Dataset:
[87 44 65 94 43 59 63 79 68 97 54 63 48 65 86]
---------------------------------------------
Highest Marks : 97
Lowest Marks  : 43
Average Marks : 67.67
---------------------------------------------
Number of students scoring above average: 6
Marks of students scoring above average:
[87 94 79 68 97 86]
