In [3]:
Pip install numpy


SyntaxError: invalid syntax (2565511063.py, line 1)

In [ ]:
import numpy as np

In [ ]:
lst=[1,2,3,4]
arr= np.array(lst) #convert list to array
print(arr1)
print(len(arr1))

[1 2 3 4]
4


In [ ]:
arr= np.array([1,2,3,4,5])
print(arr, type(arr))
print(arr[0])
print(arr[-1])
print(arr[0]+arr[1])


[1 2 3 4 5] <class 'numpy.ndarray'>
1
5
3


In [17]:
ls=list(range(60))
arr=np.array(ls)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]


In [20]:
print("shape of array:", arr.shape)
print("size of array:", arr.size)
print("data type of array:", arr.dtype)
print("no of dimensions: ", arr.ndim)

shape of array: (60,)
size of array: 60
data type of array: int64
no of dimensions:  1


In [28]:
arr1=(arr.reshape(12,5))
print(arr1)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


In [45]:
arr1[8:10, 2:4]

array([[42, 43],
       [47, 48]])

In [32]:
arr1[0:1,0:1]


array([[0]])

In [34]:
arr1[1:2, 2:4]

array([[7, 8]])

In [39]:
arr1[-1,-1]


np.int64(59)

In [43]:
arr1[11,4]

np.int64(59)

In [12]:
arrz= np.zeros(10)
print(arrz)
arr= np.ones(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
arr= np.ones((5,10)) #5 rows and 10 columns
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
arr.dtype

dtype('float64')

In [51]:
arr= np.array(range(225))
print("shape of array:", arr.shape)
print("size of array:", arr.size)
print("data type of array:", arr.dtype)
print("no of dimensions: ", arr.ndim)
arr2=arr.reshape(5,15,3)
print(arr2)


shape of array: (225,)
size of array: 225
data type of array: int64
no of dimensions:  1
[[[  0   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]
  [ 12  13  14]
  [ 15  16  17]
  [ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]
  [ 30  31  32]
  [ 33  34  35]
  [ 36  37  38]
  [ 39  40  41]
  [ 42  43  44]]

 [[ 45  46  47]
  [ 48  49  50]
  [ 51  52  53]
  [ 54  55  56]
  [ 57  58  59]
  [ 60  61  62]
  [ 63  64  65]
  [ 66  67  68]
  [ 69  70  71]
  [ 72  73  74]
  [ 75  76  77]
  [ 78  79  80]
  [ 81  82  83]
  [ 84  85  86]
  [ 87  88  89]]

 [[ 90  91  92]
  [ 93  94  95]
  [ 96  97  98]
  [ 99 100 101]
  [102 103 104]
  [105 106 107]
  [108 109 110]
  [111 112 113]
  [114 115 116]
  [117 118 119]
  [120 121 122]
  [123 124 125]
  [126 127 128]
  [129 130 131]
  [132 133 134]]

 [[135 136 137]
  [138 139 140]
  [141 142 143]
  [144 145 146]
  [147 148 149]
  [150 151 152]
  [153 154 155]
  [156 157 158]
  [159 160 161]
  [162 163 164]
  [165 166 167]
  [168 16

In [60]:
arr2[0:,0:1,0:1]


array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [63]:
arr2[0:, 0:2,0:2]

array([[[  0,   1],
        [  3,   4]],

       [[ 45,  46],
        [ 48,  49]],

       [[ 90,  91],
        [ 93,  94]],

       [[135, 136],
        [138, 139]],

       [[180, 181],
        [183, 184]]])

In [ ]:
arr2.ravel() #The numpy.ravel() function flattens a multi-dimensional array into a one-dimensional array. It returns a contiguous flattened view of the original data whenever possible, making it highly memory-efficient.

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [66]:
arr=np.random.randint(1,10,5)
print(arr)

[2 3 1 5 6]


In [71]:
arr=np.random.randint(1,10,(5,10))
print(arr)

[[5 6 6 4 5 9 4 2 5 7]
 [9 1 5 1 5 5 7 8 4 3]
 [5 2 9 6 9 5 4 4 7 4]
 [5 4 9 6 5 5 3 5 4 1]
 [8 2 5 5 5 5 1 5 4 3]]


In [ ]:
arr=np.random.normal(10) #diff value evrytime
print(arr)

11.039811181359525


In [ ]:
np.linspace(1,5,10) #doesn't allow tuple

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [72]:
arr*2


array([[10, 12, 12,  8, 10, 18,  8,  4, 10, 14],
       [18,  2, 10,  2, 10, 10, 14, 16,  8,  6],
       [10,  4, 18, 12, 18, 10,  8,  8, 14,  8],
       [10,  8, 18, 12, 10, 10,  6, 10,  8,  2],
       [16,  4, 10, 10, 10, 10,  2, 10,  8,  6]], dtype=int32)

In [ ]:
arr2=np.arange(12)
arr2+2
arr2-2
arr*arr